#!/bin/bash

BIN=/bin

#------------------------------------------------------------
# Minimum Time
#------------------------------------------------------------
TMIN=2.0
#------------------------------------------------------------

#------------------------------------------------------------
# Validation = Enable (T) , Disable (F)
#------------------------------------------------------------
TEST=F
#------------------------------------------------------------

#------------------------------------------------------------
# Matrix Path
#------------------------------------------------------------
PREFIX="/mnt/sparseUSB/sparse_matrix/MM/"
#PREFIX="/home/hmartinez/workspace/driverSPMV.backup/matrix/"
#PATH="general_matrix.txt"
PATH="symmetric_matrix.txt"
#------------------------------------------------------------

#------------------------------------------------------------
# Output Path
#------------------------------------------------------------
LOGS="logs"
#------------------------------------------------------------

$BIN/mkdir -p $LOGS

id=$($BIN/ls $LOGS | /usr/$BIN/wc -l)
LOGS=$LOGS"/log_"$id".csv"

line=$($BIN/cat Makefile.inc | $BIN/grep "LIB_SELECT" | $BIN/grep GINKGO | /usr/$BIN/wc -l)

if [ $line -eq 1 ] ; then 
  export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
fi

/usr/$BIN/taskset -c 0 ./build/spmv_driver $TMIN $TEST $PATH $LOGS "$PREFIX"

